# Generated by Django 2.1.7 on 2019-04-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp', '0002_opinionpoll_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='opinionpoll',
            name='poll_date',
            field=models.DateField(auto_now=True),
        ),
    ]
