# Generated by Django 2.1.7 on 2019-04-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp', '0004_authormanager_editormanager_persona'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonA',
            new_name='APersonA',
        ),
    ]
