# Generated by Django 2.2 on 2019-10-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageapp', '0005_auto_20190416_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorManager',
        ),
        migrations.DeleteModel(
            name='EditorManager',
        ),
    ]
