# Generated by Django 2.1.7 on 2019-03-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodels', '0004_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name="person's first name"),
        ),
    ]
