# Generated by Django 2.1.7 on 2019-03-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodels', '0006_auto_20190328_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
