# Generated by Django 2.1.7 on 2019-03-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodels', '0007_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('home_group', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'student_info',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
